exclude: ['grunt.js', 'node_modules', 'src']
auto: true

production: true 

title: 'Pharos'
subtitle: 'Get Back to Where You Were'
author:
  name: 'Jake Harding'
  email: 'jacob.s.harding@gmail.com'
  twitter: 'JakeHarding'
  github: 'jharding'

newsletter_post_url: 'http://pharosapp.us5.list-manage.com/subscribe/post?u=84b410bd0176b95cf429c4171&amp;id=2bf83a08fd'
