exclude: ['grunt.js', 'node_modules', 'src']
auto: true

production: true 

title: 'Pharos'
subtitle: 'Clever tagline.'
author:
  name: 'Jake Harding'
  email: 'jacob.s.harding@gmail.com'
  twitter: 'JakeHarding'
  github: 'jharding'
